version: '3.8'

services:
  sing-box:
    container_name: sing-box
    image: itdoginfo/sing-box:test
    build:
      context: .
      args:
        RELEASE: v1.6.0
    ports:
      - "443:443"
    environment:
      PROTOCOL: proto
      PASS: "pass"
      SERVER: domain\ip
    restart: always
    # Enable for custom config (multiple accounts for example)
    # volumes:
    #  - ./config:/etc/sing-box/